package gov.uspto.patent.ptab.entities;

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StndWidget generated by hbm2java
 */
@Entity
@Table(name = "STND_WIDGET", uniqueConstraints = @UniqueConstraint(columnNames = "WIDGET_NM"))
public class StndWidget implements java.io.Serializable {

    private int widgetId;
    private String widgetNm;
    private int fkWidgetSubcategoryId;
    private String descriptionTx;
    private String noteTx;
    private char recentIn;
    private char defaultIn;
    private Long defaultPositionNo;
    private String linkUrlTx;
    private String typeTx;
    private String configTx;
    private Date beginEffectiveDt;
    private Date endEffectiveDt;
    private Date createTs;
    private long createUserId;
    private Date lastModTs;
    private long lastModUserId;
    private long lockControlNo;
    private int displayOrderSequenceNo;
    private Clob columnListDoc;
    private Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets = new HashSet<UserWorkspaceWidgetEntity>(0);

    public StndWidget() {
    }

    public StndWidget(final int widgetId, final String widgetNm, final int fkWidgetSubcategoryId, final String descriptionTx,
            final char recentIn, final char defaultIn, final String typeTx, final String configTx,
            final Date beginEffectiveDt, final Date createTs, final long createUserId, final Date lastModTs,
            final long lastModUserId, final long lockControlNo, final int displayOrderSequenceNo) {
        this.widgetId = widgetId;
        this.widgetNm = widgetNm;
        this.fkWidgetSubcategoryId = fkWidgetSubcategoryId;
        this.descriptionTx = descriptionTx;
        this.recentIn = recentIn;
        this.defaultIn = defaultIn;
        this.typeTx = typeTx;
        this.configTx = configTx;
        this.beginEffectiveDt = beginEffectiveDt;
        this.createTs = createTs;
        this.createUserId = createUserId;
        this.lastModTs = lastModTs;
        this.lastModUserId = lastModUserId;
        this.lockControlNo = lockControlNo;
        this.displayOrderSequenceNo = displayOrderSequenceNo;
    }

    public StndWidget(final int widgetId, final String widgetNm, final int fkWidgetSubcategoryId, final String descriptionTx,
            final String noteTx, final char recentIn, final char defaultIn, final Long defaultPositionNo,
            final String linkUrlTx, final String typeTx, final String configTx, final Date beginEffectiveDt,
            final Date endEffectiveDt, final Date createTs, final long createUserId, final Date lastModTs,
            final long lastModUserId, final long lockControlNo, final int displayOrderSequenceNo, final Clob columnListDoc,
            final Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets) {
        this.widgetId = widgetId;
        this.widgetNm = widgetNm;
        this.fkWidgetSubcategoryId = fkWidgetSubcategoryId;
        this.descriptionTx = descriptionTx;
        this.noteTx = noteTx;
        this.recentIn = recentIn;
        this.defaultIn = defaultIn;
        this.defaultPositionNo = defaultPositionNo;
        this.linkUrlTx = linkUrlTx;
        this.typeTx = typeTx;
        this.configTx = configTx;
        this.beginEffectiveDt = beginEffectiveDt;
        this.endEffectiveDt = endEffectiveDt;
        this.createTs = createTs;
        this.createUserId = createUserId;
        this.lastModTs = lastModTs;
        this.lastModUserId = lastModUserId;
        this.lockControlNo = lockControlNo;
        this.displayOrderSequenceNo = displayOrderSequenceNo;
        this.columnListDoc = columnListDoc;
        this.userWorkspaceWidgets = userWorkspaceWidgets;
    }

    @Id

    @Column(name = "WIDGET_ID", unique = true, nullable = false, precision = 5, scale = 0)
    public int getWidgetId() {
        return this.widgetId;
    }

    public void setWidgetId(final int widgetId) {
        this.widgetId = widgetId;
    }

    @Column(name = "WIDGET_NM", unique = true, nullable = false, length = 200)
    public String getWidgetNm() {
        return this.widgetNm;
    }

    public void setWidgetNm(final String widgetNm) {
        this.widgetNm = widgetNm;
    }

    @Column(name = "FK_WIDGET_SUBCATEGORY_ID", nullable = false, precision = 5, scale = 0)
    public int getFkWidgetSubcategoryId() {
        return this.fkWidgetSubcategoryId;
    }

    public void setFkWidgetSubcategoryId(final int fkWidgetSubcategoryId) {
        this.fkWidgetSubcategoryId = fkWidgetSubcategoryId;
    }

    @Column(name = "DESCRIPTION_TX", nullable = false, length = 320)
    public String getDescriptionTx() {
        return this.descriptionTx;
    }

    public void setDescriptionTx(final String descriptionTx) {
        this.descriptionTx = descriptionTx;
    }

    @Column(name = "NOTE_TX", length = 320)
    public String getNoteTx() {
        return this.noteTx;
    }

    public void setNoteTx(final String noteTx) {
        this.noteTx = noteTx;
    }

    @Column(name = "RECENT_IN", nullable = false, length = 1)
    public char getRecentIn() {
        return this.recentIn;
    }

    public void setRecentIn(final char recentIn) {
        this.recentIn = recentIn;
    }

    @Column(name = "DEFAULT_IN", nullable = false, length = 1)
    public char getDefaultIn() {
        return this.defaultIn;
    }

    public void setDefaultIn(final char defaultIn) {
        this.defaultIn = defaultIn;
    }

    @Column(name = "DEFAULT_POSITION_NO", precision = 10, scale = 0)
    public Long getDefaultPositionNo() {
        return this.defaultPositionNo;
    }

    public void setDefaultPositionNo(final Long defaultPositionNo) {
        this.defaultPositionNo = defaultPositionNo;
    }

    @Column(name = "LINK_URL_TX", length = 320)
    public String getLinkUrlTx() {
        return this.linkUrlTx;
    }

    public void setLinkUrlTx(final String linkUrlTx) {
        this.linkUrlTx = linkUrlTx;
    }

    @Column(name = "TYPE_TX", nullable = false, length = 30)
    public String getTypeTx() {
        return this.typeTx;
    }

    public void setTypeTx(final String typeTx) {
        this.typeTx = typeTx;
    }

    @Column(name = "CONFIG_TX", nullable = false, length = 4000)
    public String getConfigTx() {
        return this.configTx;
    }

    public void setConfigTx(final String configTx) {
        this.configTx = configTx;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "BEGIN_EFFECTIVE_DT", nullable = false, length = 7)
    public Date getBeginEffectiveDt() {
        return this.beginEffectiveDt;
    }

    public void setBeginEffectiveDt(final Date beginEffectiveDt) {
        this.beginEffectiveDt = beginEffectiveDt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "END_EFFECTIVE_DT", length = 7)
    public Date getEndEffectiveDt() {
        return this.endEffectiveDt;
    }

    public void setEndEffectiveDt(final Date endEffectiveDt) {
        this.endEffectiveDt = endEffectiveDt;
    }

    @Column(name = "CREATE_TS", nullable = false)
    public Date getCreateTs() {
        return this.createTs;
    }

    public void setCreateTs(final Date createTs) {
        this.createTs = createTs;
    }

    @Column(name = "CREATE_USER_ID", nullable = false, precision = 10, scale = 0)
    public long getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(final long createUserId) {
        this.createUserId = createUserId;
    }

    @Column(name = "LAST_MOD_TS", nullable = false)
    public Date getLastModTs() {
        return this.lastModTs;
    }

    public void setLastModTs(final Date lastModTs) {
        this.lastModTs = lastModTs;
    }

    @Column(name = "LAST_MOD_USER_ID", nullable = false, precision = 10, scale = 0)
    public long getLastModUserId() {
        return this.lastModUserId;
    }

    public void setLastModUserId(final long lastModUserId) {
        this.lastModUserId = lastModUserId;
    }

    @Column(name = "LOCK_CONTROL_NO", nullable = false, precision = 10, scale = 0)
    public long getLockControlNo() {
        return this.lockControlNo;
    }

    public void setLockControlNo(final long lockControlNo) {
        this.lockControlNo = lockControlNo;
    }

    @Column(name = "DISPLAY_ORDER_SEQUENCE_NO", nullable = false, precision = 5, scale = 0)
    public int getDisplayOrderSequenceNo() {
        return this.displayOrderSequenceNo;
    }

    public void setDisplayOrderSequenceNo(final int displayOrderSequenceNo) {
        this.displayOrderSequenceNo = displayOrderSequenceNo;
    }

    @Column(name = "COLUMN_LIST_DOC")
    public Clob getColumnListDoc() {
        return this.columnListDoc;
    }

    public void setColumnListDoc(final Clob columnListDoc) {
        this.columnListDoc = columnListDoc;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "stndWidget")
    public Set<UserWorkspaceWidgetEntity> getUserWorkspaceWidgets() {
        return this.userWorkspaceWidgets;
    }

    public void setUserWorkspaceWidgets(final Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets) {
        this.userWorkspaceWidgets = userWorkspaceWidgets;
    }

}
