package gov.uspto.patent.ptab.entities;

import java.sql.Clob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserWorkspaceWidget generated by hbm2java
 */
@Entity
@Table(name = "USER_WORKSPACE_WIDGET", uniqueConstraints = @UniqueConstraint(columnNames = { "FK_USER_WORKSPACE_ID",
		"WIDGET_CUSTOM_NM" }))
public class UserWorkspaceWidgetEntity implements java.io.Serializable {

	private long userWorkspaceWidgetId;
	private UserWorkspaceEntity userWorkspace;
	private StndWidget stndWidget;
	private String widgetCustomNm;
	private String widgetPositionTx;
	private Integer widgetHeightPixelQt;
	private String configTx;
	private String widgetColorNm;
	private Date createTs;
	private long createUserId;
	private Date lastModTs;
	private long lastModUserId;
	private long lockControlNo;
	private String queryTx;
	private Clob selectedColumnListDoc;

	public UserWorkspaceWidgetEntity() {
	}

	public UserWorkspaceWidgetEntity(final long userWorkspaceWidgetId, final UserWorkspaceEntity userWorkspace,
			final StndWidget stndWidget, final String widgetCustomNm, final String widgetPositionTx,
			final String widgetColorNm, final Date createTs, final long createUserId, final Date lastModTs,
			final long lastModUserId, final long lockControlNo) {
		this.userWorkspaceWidgetId = userWorkspaceWidgetId;
		this.userWorkspace = userWorkspace;
		this.stndWidget = stndWidget;
		this.widgetCustomNm = widgetCustomNm;
		this.widgetPositionTx = widgetPositionTx;
		this.widgetColorNm = widgetColorNm;
		this.createTs = createTs;
		this.createUserId = createUserId;
		this.lastModTs = lastModTs;
		this.lastModUserId = lastModUserId;
		this.lockControlNo = lockControlNo;
	}

	public UserWorkspaceWidgetEntity(final long userWorkspaceWidgetId, final UserWorkspaceEntity userWorkspace,
			final StndWidget stndWidget, final String widgetCustomNm, final String widgetPositionTx,
			final Integer widgetHeightPixelQt, final String configTx, final String widgetColorNm, final Date createTs,
			final long createUserId, final Date lastModTs, final long lastModUserId, final long lockControlNo,
			final String queryTx, final Clob selectedColumnListDoc) {
		this.userWorkspaceWidgetId = userWorkspaceWidgetId;
		this.userWorkspace = userWorkspace;
		this.stndWidget = stndWidget;
		this.widgetCustomNm = widgetCustomNm;
		this.widgetPositionTx = widgetPositionTx;
		this.widgetHeightPixelQt = widgetHeightPixelQt;
		this.configTx = configTx;
		this.widgetColorNm = widgetColorNm;
		this.createTs = createTs;
		this.createUserId = createUserId;
		this.lastModTs = lastModTs;
		this.lastModUserId = lastModUserId;
		this.lockControlNo = lockControlNo;
		this.queryTx = queryTx;
		this.selectedColumnListDoc = selectedColumnListDoc;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "USER_WORKSPACE_WIDGET_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getUserWorkspaceWidgetId() {
		return this.userWorkspaceWidgetId;
	}

	public void setUserWorkspaceWidgetId(final long userWorkspaceWidgetId) {
		this.userWorkspaceWidgetId = userWorkspaceWidgetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_USER_WORKSPACE_ID", nullable = false)
	public UserWorkspaceEntity getUserWorkspace() {
		return this.userWorkspace;
	}

	public void setUserWorkspace(final UserWorkspaceEntity userWorkspace) {
		this.userWorkspace = userWorkspace;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_WIDGET_ID", nullable = false)
	public StndWidget getStndWidget() {
		return this.stndWidget;
	}

	public void setStndWidget(final StndWidget stndWidget) {
		this.stndWidget = stndWidget;
	}

	@Column(name = "WIDGET_CUSTOM_NM", nullable = false, length = 200)
	public String getWidgetCustomNm() {
		return this.widgetCustomNm;
	}

	public void setWidgetCustomNm(final String widgetCustomNm) {
		this.widgetCustomNm = widgetCustomNm;
	}

	@Column(name = "WIDGET_POSITION_TX", nullable = false, length = 50)
	public String getWidgetPositionTx() {
		return this.widgetPositionTx;
	}

	public void setWidgetPositionTx(final String widgetPositionTx) {
		this.widgetPositionTx = widgetPositionTx;
	}

	@Column(name = "WIDGET_HEIGHT_PIXEL_QT", precision = 5, scale = 0)
	public Integer getWidgetHeightPixelQt() {
		return this.widgetHeightPixelQt;
	}

	public void setWidgetHeightPixelQt(final Integer widgetHeightPixelQt) {
		this.widgetHeightPixelQt = widgetHeightPixelQt;
	}

	@Column(name = "CONFIG_TX", length = 4000)
	public String getConfigTx() {
		return this.configTx;
	}

	public void setConfigTx(final String configTx) {
		this.configTx = configTx;
	}

	@Column(name = "WIDGET_COLOR_NM", nullable = false, length = 50)
	public String getWidgetColorNm() {
		return this.widgetColorNm;
	}

	public void setWidgetColorNm(final String widgetColorNm) {
		this.widgetColorNm = widgetColorNm;
	}

	@Column(name = "CREATE_TS", nullable = false)
	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(final Date createTs) {
		this.createTs = createTs;
	}

	@Column(name = "CREATE_USER_ID", nullable = false, precision = 10, scale = 0)
	public long getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(final long createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "LAST_MOD_TS", nullable = false)
	public Date getLastModTs() {
		return this.lastModTs;
	}

	public void setLastModTs(final Date lastModTs) {
		this.lastModTs = lastModTs;
	}

	@Column(name = "LAST_MOD_USER_ID", nullable = false, precision = 10, scale = 0)
	public long getLastModUserId() {
		return this.lastModUserId;
	}

	public void setLastModUserId(final long lastModUserId) {
		this.lastModUserId = lastModUserId;
	}

	@Column(name = "LOCK_CONTROL_NO", nullable = false, precision = 10, scale = 0)
	public long getLockControlNo() {
		return this.lockControlNo;
	}

	public void setLockControlNo(final long lockControlNo) {
		this.lockControlNo = lockControlNo;
	}

	@Column(name = "QUERY_TX", length = 2000)
	public String getQueryTx() {
		return this.queryTx;
	}

	public void setQueryTx(final String queryTx) {
		this.queryTx = queryTx;
	}

	@Column(name = "SELECTED_COLUMN_LIST_DOC")
	public Clob getSelectedColumnListDoc() {
		return this.selectedColumnListDoc;
	}

	public void setSelectedColumnListDoc(final Clob selectedColumnListDoc) {
		this.selectedColumnListDoc = selectedColumnListDoc;
	}

}
