package gov.uspto.patent.ptab.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * UserFavoriteLink generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "USER_FAVORITE_LINK")
public class UserFavoriteLink implements java.io.Serializable {
    private static final long serialVersionUID = 4169631761242818537L;

    @Id
    @Column(name = "USER_FAVORITE_LINK_ID", unique = true, nullable = false, precision = 10, scale = 0)
    private Long userFavoriteLinkIdentifier;

    @Column(name = "FK_APPLICATION_USER_ID")
    private Long applicationUserIdentifier;

    @Column(name = "FAVORITE_NM")
    private String userFavoriteName;

    @Column(name = "FAVORITE_URL_TX")
    private String userFavoriteUrlText;

    @Column(name = "FAVORITE_PRIORITY_NO")
    private Long favoritePriorityNumber;

    @Column(name = "BEGIN_EFFECTIVE_DT")
    private Date beginEffectiveDate;

    @Column(name = "END_EFFECTIVE_DT")
    private Date endEffectiveDate;

    @Column(name = "CREATE_TS")
    private Date createTimeStamp;

    @Column(name = "CREATE_USER_ID")
    private Long createUserIdentifier;

    @Column(name = "LAST_MOD_TS")
    private Date lastModTimeStamp;

    @Column(name = "LAST_MOD_USER_ID")
    private Long lastModUserIdentifier;

    @Column(name = "LOCK_CONTROL_NO")
    private Long lockControlNumber;

    @Column(name = "ROLE_FAVORITE_LINK_ID")
    private Long roleFavoriteLinkIdentifier;

}
