package gov.uspto.patent.ptab.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserWorkspace generated by hbm2java
 */
@Entity
@Table(name = "USER_WORKSPACE", uniqueConstraints = @UniqueConstraint(columnNames = { "FK_APPLICATION_USER_ID",
        "USER_WORKSPACE_NM" }))
public class UserWorkspaceEntity implements java.io.Serializable {

    private long userWorkspaceId;
    private long fkApplicationUserId;
    private String userWorkspaceNm;
    private String viewLayoutNm;
    private char defaultIn;
    private int orderSequenceNo;
    private String descriptionTx;
    private String configTx;
    private Date createTs;
    private long createUserId;
    private Date lastModTs;
    private long lastModUserId;
    private long lockControlNo;
    private Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets = new HashSet<UserWorkspaceWidgetEntity>(0);

    public UserWorkspaceEntity() {
    }

    public UserWorkspaceEntity(final long userWorkspaceId, final long fkApplicationUserId, final String userWorkspaceNm,
            final String viewLayoutNm, final char defaultIn, final int orderSequenceNo, final Date createTs,
            final long createUserId, final Date lastModTs, final long lastModUserId, final long lockControlNo) {
        this.userWorkspaceId = userWorkspaceId;
        this.fkApplicationUserId = fkApplicationUserId;
        this.userWorkspaceNm = userWorkspaceNm;
        this.viewLayoutNm = viewLayoutNm;
        this.defaultIn = defaultIn;
        this.orderSequenceNo = orderSequenceNo;
        this.createTs = createTs;
        this.createUserId = createUserId;
        this.lastModTs = lastModTs;
        this.lastModUserId = lastModUserId;
        this.lockControlNo = lockControlNo;
    }

    public UserWorkspaceEntity(final long userWorkspaceId, final long fkApplicationUserId, final String userWorkspaceNm,
            final String viewLayoutNm, final char defaultIn, final int orderSequenceNo, final String descriptionTx,
            final String configTx, final Date createTs, final long createUserId, final Date lastModTs,
            final long lastModUserId, final long lockControlNo, final Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets) {
        this.userWorkspaceId = userWorkspaceId;
        this.fkApplicationUserId = fkApplicationUserId;
        this.userWorkspaceNm = userWorkspaceNm;
        this.viewLayoutNm = viewLayoutNm;
        this.defaultIn = defaultIn;
        this.orderSequenceNo = orderSequenceNo;
        this.descriptionTx = descriptionTx;
        this.configTx = configTx;
        this.createTs = createTs;
        this.createUserId = createUserId;
        this.lastModTs = lastModTs;
        this.lastModUserId = lastModUserId;
        this.lockControlNo = lockControlNo;
        this.userWorkspaceWidgets = userWorkspaceWidgets;
    }

    @Id
    @Column(name = "USER_WORKSPACE_ID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getUserWorkspaceId() {
        return this.userWorkspaceId;
    }

    public void setUserWorkspaceId(final long userWorkspaceId) {
        this.userWorkspaceId = userWorkspaceId;
    }

    @Column(name = "FK_APPLICATION_USER_ID", nullable = false, precision = 10, scale = 0)
    public long getFkApplicationUserId() {
        return this.fkApplicationUserId;
    }

    public void setFkApplicationUserId(final long fkApplicationUserId) {
        this.fkApplicationUserId = fkApplicationUserId;
    }

    @Column(name = "USER_WORKSPACE_NM", nullable = false, length = 50)
    public String getUserWorkspaceNm() {
        return this.userWorkspaceNm;
    }

    public void setUserWorkspaceNm(final String userWorkspaceNm) {
        this.userWorkspaceNm = userWorkspaceNm;
    }

    @Column(name = "VIEW_LAYOUT_NM", nullable = false, length = 50)
    public String getViewLayoutNm() {
        return this.viewLayoutNm;
    }

    public void setViewLayoutNm(final String viewLayoutNm) {
        this.viewLayoutNm = viewLayoutNm;
    }

    @Column(name = "DEFAULT_IN", nullable = false, length = 1)
    public char getDefaultIn() {
        return this.defaultIn;
    }

    public void setDefaultIn(final char defaultIn) {
        this.defaultIn = defaultIn;
    }

    @Column(name = "ORDER_SEQUENCE_NO", nullable = false, precision = 5, scale = 0)
    public int getOrderSequenceNo() {
        return this.orderSequenceNo;
    }

    public void setOrderSequenceNo(final int orderSequenceNo) {
        this.orderSequenceNo = orderSequenceNo;
    }

    @Column(name = "DESCRIPTION_TX", length = 320)
    public String getDescriptionTx() {
        return this.descriptionTx;
    }

    public void setDescriptionTx(final String descriptionTx) {
        this.descriptionTx = descriptionTx;
    }

    @Column(name = "CONFIG_TX", length = 4000)
    public String getConfigTx() {
        return this.configTx;
    }

    public void setConfigTx(final String configTx) {
        this.configTx = configTx;
    }

    @Column(name = "CREATE_TS", nullable = false)
    public Date getCreateTs() {
        return this.createTs;
    }

    public void setCreateTs(final Date createTs) {
        this.createTs = createTs;
    }

    @Column(name = "CREATE_USER_ID", nullable = false, precision = 10, scale = 0)
    public long getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(final long createUserId) {
        this.createUserId = createUserId;
    }

    @Column(name = "LAST_MOD_TS", nullable = false)
    public Date getLastModTs() {
        return this.lastModTs;
    }

    public void setLastModTs(final Date lastModTs) {
        this.lastModTs = lastModTs;
    }

    @Column(name = "LAST_MOD_USER_ID", nullable = false, precision = 10, scale = 0)
    public long getLastModUserId() {
        return this.lastModUserId;
    }

    public void setLastModUserId(final long lastModUserId) {
        this.lastModUserId = lastModUserId;
    }

    @Column(name = "LOCK_CONTROL_NO", nullable = false, precision = 10, scale = 0)
    public long getLockControlNo() {
        return this.lockControlNo;
    }

    public void setLockControlNo(final long lockControlNo) {
        this.lockControlNo = lockControlNo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userWorkspace")
    public Set<UserWorkspaceWidgetEntity> getUserWorkspaceWidgets() {
        return this.userWorkspaceWidgets;
    }

    public void setUserWorkspaceWidgets(final Set<UserWorkspaceWidgetEntity> userWorkspaceWidgets) {
        this.userWorkspaceWidgets = userWorkspaceWidgets;
    }

}
